name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
                        cmake \
                        build-essential \
                        zip \
                        git \
                        ca-certificates \
                        curl \
                        python3 \
                        ninja-build \
                        pkg-config \
                        cargo

      - name: Configure
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Install to staging
        run: cmake --install build --prefix "${{ github.workspace }}/stage"

      - name: Create zip artifact for c8
        run: |
          cd stage
          zip -r ../c8-linux-x86_64.zip .

      - name: Upload artifact for c8
        uses: actions/upload-artifact@v4
        with:
          name: c8-linux-x86_64
          path: c8-linux-x86_64.zip

      - name: Create zip artifact for v8
        run: |
          cd build/v8-install
          zip -r ../../v8-linux-x86_64.zip .

      - name: Upload artifact for v8
        uses: actions/upload-artifact@v4
        with:
          name: v8-linux-x86_64
          path: v8-linux-x86_64.zip


